name: test main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.x'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip

          - name: Test with pytest
            run: |
              python -m unittest discover -s ./